### ISSUE TITLE
Chooser modal functionality

### ISSUE THREAD

**Issue by urlsangel** [takeflight/wagtailmodelchooser#2]
Hi @timheap 

I've implemented the model chooser, but the ModelChooserPanel window doesn't look like it works the same as the SnippetChooserPanel.

Specifically: it's missing the title of the model; the model name that appears with "There are no" is singular, rather than plural; and there's no link to create an instance if none are found.

Here's an example with a model called "CTA":

![screen shot 2016-12-08 at 13 38 40](https://cloud.githubusercontent.com/assets/560463/21012081/43f004d0-bd4c-11e6-83d5-0076d576d028.png)

I'm not sure if there are underlying reasons for the differing implementation?

Thanks,

Russell.

**Comment by timheap** [comment]
The missing / incorrect names of the models are a bug that needs fixing.

The lack of a create button is tricky. The picker can be used to pick specific page types, snippets, users, and even models that are not editable in the Wagtail admin. There is no simple way of adding an create button, because the ways of creating models are not consistent, or even guaranteed to exist. A "create url" option could be added that causes a button to appear in this interface.

**Comment by urlsangel** [comment]
Hi Tim

I was thinking that was the case with the create button. I was looking to use this in assocaition with wagtail model admin, so as to avoid things appearing twice (i.e. in snippets).

The optional create URL would make sense in that case, as the onus would then be on the developer to support that create view somehow.

**Comment by lucasmoeskops** [comment]
I made https://github.com/takeflight/wagtailmodelchooser/pull/5 to fix the singular labels.
